language: ruby
rvm:
  - 1.9.3
notifications:
  recipients:
    - jari.bakken@gmail.com
  irc:
    channels:
      - "irc.freenode.net#holderdeord"
    on_success: change
    on_failure: change
    template:
      - "%{author} | %{commit} | %{message} | %{build_url}"
script: "bundle exec rake"