language: ruby
rvm:
  - 2.2.0
notifications:
  recipients:
    - jari@holderdeord.no
  irc:
    channels:
      - "irc.freenode.net#holderdeord"
    on_success: always
    on_failure: change
    template:
      - "%{author} | %{commit} | %{message} | %{build_url}"
script: "SPEC_OPTS=--backtrace bundle exec rake"
