Feature: Import data
    Scenario: Import districts
      Given a file named "fylker.xml" with:
      """
      <?xml version="1.0" encoding="utf-8"?>
      <fylker_oversikt xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://data.stortinget.no">
        <versjon>1.0</versjon>
        <fylker_liste>
          <fylke>
            <versjon>1.0</versjon>
            <id>AA</id>
            <navn>Aust-Agder</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>VA</id>
            <navn>Vest-Agder</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>Ak</id>
            <navn>Akershus</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>Bu</id>
            <navn>Buskerud</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>Fi</id>
            <navn>Finnmark</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>He</id>
            <navn>Hedmark</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>Ho</id>
            <navn>Hordaland</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>MR</id>
            <navn>Møre og Romsdal</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>No</id>
            <navn>Nordland</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>Op</id>
            <navn>Oppland</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>Os</id>
            <navn>Oslo</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>Ro</id>
            <navn>Rogaland</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>SF</id>
            <navn>Sogn og Fjordane</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>Te</id>
            <navn>Telemark</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>Tr</id>
            <navn>Troms</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>NT</id>
            <navn>Nord-Trøndelag</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>ST</id>
            <navn>Sør-Trøndelag</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>Ve</id>
            <navn>Vestfold</navn>
          </fylke>
          <fylke>
            <versjon>1.0</versjon>
            <id>Øs</id>
            <navn>Østfold</navn>
          </fylke>
        </fylker_liste>
      </fylker_oversikt>
      """
      When I run `hdo-converter districts fylker.xml`
      Then the stdout should contain:
      """
      <?xml version="1.0" encoding="UTF-8"?>
      <districts>
        <district>
          <externalId>AA</externalId>
          <name>Aust-Agder</name>
        </district>
        <district>
          <externalId>VA</externalId>
          <name>Vest-Agder</name>
        </district>
        <district>
          <externalId>Ak</externalId>
          <name>Akershus</name>
        </district>
        <district>
          <externalId>Bu</externalId>
          <name>Buskerud</name>
        </district>
        <district>
          <externalId>Fi</externalId>
          <name>Finnmark</name>
        </district>
        <district>
          <externalId>He</externalId>
          <name>Hedmark</name>
        </district>
        <district>
          <externalId>Ho</externalId>
          <name>Hordaland</name>
        </district>
        <district>
          <externalId>MR</externalId>
          <name>Møre og Romsdal</name>
        </district>
        <district>
          <externalId>No</externalId>
          <name>Nordland</name>
        </district>
        <district>
          <externalId>Op</externalId>
          <name>Oppland</name>
        </district>
        <district>
          <externalId>Os</externalId>
          <name>Oslo</name>
        </district>
        <district>
          <externalId>Ro</externalId>
          <name>Rogaland</name>
        </district>
        <district>
          <externalId>SF</externalId>
          <name>Sogn og Fjordane</name>
        </district>
        <district>
          <externalId>Te</externalId>
          <name>Telemark</name>
        </district>
        <district>
          <externalId>Tr</externalId>
          <name>Troms</name>
        </district>
        <district>
          <externalId>NT</externalId>
          <name>Nord-Trøndelag</name>
        </district>
        <district>
          <externalId>ST</externalId>
          <name>Sør-Trøndelag</name>
        </district>
        <district>
          <externalId>Ve</externalId>
          <name>Vestfold</name>
        </district>
        <district>
          <externalId>Øs</externalId>
          <name>Østfold</name>
        </district>
      </districts>
      """