Feature: Import data
    Scenario: Import districts
      When I run `hdo-converter --only-print districts`
      Then the stdout should contain:
      """
      <?xml version="1.0" encoding="UTF-8"?>
      <districts>
        <district>
          <externalId>Ak</externalId>
          <name>Akershus</name>
        </district>
        <district>
          <externalId>AA</externalId>
          <name>Aust-Agder</name>
        </district>
        <district>
          <externalId>Bu</externalId>
          <name>Buskerud</name>
        </district>
        <district>
          <externalId>Fi</externalId>
          <name>Finnmark</name>
        </district>
        <district>
          <externalId>He</externalId>
          <name>Hedmark</name>
        </district>
        <district>
          <externalId>Ho</externalId>
          <name>Hordaland</name>
        </district>
        <district>
          <externalId>MR</externalId>
          <name>Møre og Romsdal</name>
        </district>
        <district>
          <externalId>NT</externalId>
          <name>Nord-Trøndelag</name>
        </district>
        <district>
          <externalId>No</externalId>
          <name>Nordland</name>
        </district>
        <district>
          <externalId>Op</externalId>
          <name>Oppland</name>
        </district>
        <district>
          <externalId>Os</externalId>
          <name>Oslo</name>
        </district>
        <district>
          <externalId>Ro</externalId>
          <name>Rogaland</name>
        </district>
        <district>
          <externalId>SF</externalId>
          <name>Sogn og Fjordane</name>
        </district>
        <district>
          <externalId>ST</externalId>
          <name>Sør-Trøndelag</name>
        </district>
        <district>
          <externalId>Te</externalId>
          <name>Telemark</name>
        </district>
        <district>
          <externalId>Tr</externalId>
          <name>Troms</name>
        </district>
        <district>
          <externalId>VA</externalId>
          <name>Vest-Agder</name>
        </district>
        <district>
          <externalId>Ve</externalId>
          <name>Vestfold</name>
        </district>
        <district>
          <externalId>Øs</externalId>
          <name>Østfold</name>
        </district>
      </districts>
      """